### ISSUE TITLE
Make error in Cygwin

### ISSUE THREAD

**Issue by Eigertje** [sfu-compbio/sinvict#5]
Hi,

I'm trying to install siNVICT in Cygwin on my win7 system. I've installed all the available Boost and G++ packages available under Cygwin upon installation.
However, after the make command I get the following error:

_g++ main.o Caller.o Batch.o Location.o Sample.o ReadcountEntry.o Allele.o Filter.o Statistics.o Common.o -o sinvict -static -lz -lboost_program_options
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lboost_program_options
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/libstdc++.a(cow-stdexcept.o): In function `std::logic_error::logic_error(std::logic_error const&)':
/usr/src/debug/gcc-5.4.0-1/libstdc++-v3/src/c++11/cow-stdexcept.cc:44: multiple definition of `std::logic_error::logic_error(std::logic_error const&)'
main.o:/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/stdexcept:113: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/libstdc++.a(cow-stdexcept.o): In function `std::logic_error::logic_error(std::logic_error const&)':
/usr/src/debug/gcc-5.4.0-1/libstdc++-v3/src/c++11/cow-stdexcept.cc:44: multiple definition of `std::runtime_error::runtime_error(std::runtime_error const&)'
main.o:/home/a.brink/siNVICT/sinvict/main.cpp:19: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:17: sinvict] Error 1_

Any ideas?
I'm afraid I have little experience in compiling.

Best regards

**Comment by ckockan** [comment]
Hi Eigertje,

I don't have much experience with Cygwin but it looks like the error is due to boost. We now have a version that has no external dependencies at all (such as boost). Try the following and see if it works:

git clone https://github.com/sfu-compbio/sinvict
cd sinvict
git branch -a
git checkout devel
make

This should compile without any errors and without needing boost or any other libraries.

**Comment by Eigertje** [comment]
Thanks, no make problems now.
