### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by HaoKuo** [sfu-compbio/sinvict#6]
Hi~
I encountered an error  when i ran sinvict using command like :
./sinvict -t readcount_dir/ -o test

Segmentation fault (core dumped)

./sinvict -h went well. 

Any help about that?
Thanks a lot~

**Comment by ckockan** [comment]
Hi, that sounds like a directory/file issue to me. Can you try using absolute paths for -t and -o and see if that works? Also, the readcount_dir should only contain the actual readcount files and nothing else, so that might be the problem too. For instance, if your readcount_dir is "/home/some_project/some_experiment/readcount_dir", that directory should only contain files such as sample1.readcount, sample2.readcount, etc.

**Comment by HaoKuo** [comment]
Thanks ckockan~
I've tried the absolute paths for -t and -o and got same error "Segmentation fault (core dumped)".
There is only one test.readcount (20 lines) in the directory /home/some_project/some_experiment/readcount_dir
Perhaps I got a wrong format readcount file.
Could you please upload some test readcount files?

**Comment by ckockan** [comment]
Can you try again with these files: https://github.com/sfu-compbio/sinvict/archive/sample-data.zip

**Comment by HaoKuo** [comment]
Thanks for the super fast reply, ckockan .
Things went well with your readcount files. 
Obviously, I got a wrong format readcount file.
